import Footer from './Components/global/Footer'
import Navbar from './Components/global/Navbar'
import './globals.css'
import { Young_Serif } from 'next/font/google'

const youngSerif = Young_Serif({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={youngSerif.className}>
        <div className=' fixed top-0 bg-white pb-5 w-full z-10'>
        <Navbar />
        </div>
        <main className='mx-10 my-40'>
        {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
